[package]
name = "concurrent-sqlite-example"
version = "0.1.0"
authors = ["Andrea Venuta <venutawebdesign@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.2"
threadpool = "1.7.1"

[dependencies.rusqlite]
version = "0.20.0"
features = ["bundled"]